name: Build DiskWidget.exe
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        shell: cmd
        run: cl /nologo /O2 /EHsc /utf-8 /MT DiskWidget.cpp /link /SUBSYSTEM:WINDOWS /OUT:DiskWidget.exe
      - uses: actions/upload-artifact@v4
        with:
          name: DiskWidget
          path: DiskWidget.exe
